### PR TITLE
Try to make show images work with other languages

### PR DESCRIPTION
**Pull request by csm10495**
Match the combo of classes currently used by lemmy-ui: https://github.com/LemmyNet/lemmy-ui/blob/2911cd8cdb348629a97d60239723b1925210df0a/src/shared/components/post/post-listing.tsx#L331

### CODE REVIEW

**Comment by csm10495** [comment]
This is not really great but i think it seems to work for me in English. @Lucki can you try to see if this fixes #35?

**Comment by Lucki** [comment]
It does - but looks equally fragile :D

**Comment by howdy-tsc** [comment]
Very nice work! 👍It's better than what we have currently. Well done. Fragility still standing.

**Review by howdy-tsc — APPROVED** [review]
merging.

**Pull request merged**
